### ISSUE TITLE
Ingesting multiple files from a single page into Aleph and creating ftm entities

### ISSUE THREAD

**Issue by uhhhuh** [alephdata/funes#192]
Problem: while parsing a page, we need to ingest into an Aleph instance multiple linked files, get their ids in return, do some further processing/parsing and be able to reference the ingested files in the FtM entities created down the line (e.g. documents via Documentation to Articles).
Currently used AlephAPI.api.ingest_upload() returns the same id for multiple files from the same source page.

**Comment by sunu** [comment]
@uhhhuh I think we discussed how to solve this by designing the flow of data in the crawler itself. Let me know if we need to do anything more.
